### ISSUE TITLE
H2 or SQLite

### ISSUE THREAD

**Issue by sre42** [peterGraf/ARVOS#10]
A good read: http://www.webdevelopersdiary.com/blog/lightweight-self-contained-database-sqlite-vs-h2-database-vs-mysql-embedded

**Comment by peterGraf** [comment]
Hello Omar, interesting read, but ...
- it talks about PHP and SQLite vs H2. I think we need to look at it more from a Java perspective.
- The article does not bring any good reason not to use SQLite.
- SQLite is used inside Android for storage of local files

I would go with SQLite, if that plays well with the Spring Java framework.

**Comment by sre42** [comment]
As @peterGraf mentioned, SQLite is used in android and hence is more appropriate to use.
