### ISSUE TITLE
ARVOS must render 3D object augments

### ISSUE THREAD

**Issue by peterGraf** [peterGraf/ARVOS#3]
Object format has to be renderable on both Android and iOS
Ideally with vertex animations (autoplay and/or user triggered)
Jpg, and png and movie textures (with alpha, movies autoplay and/or user triggered)
Sound augments should be playable (autoplay and/or user triggered)

**Comment by peterGraf** [comment]
Omarasifshaikh proposed the JMonkeyEngine 3.

**Comment by peterGraf** [comment]
I looked at the Ogre 3d http://www.ogre3d.org/ library, looks pretty good.

**Comment by peterGraf** [comment]
I am looking at gameplay3d right now.

**Comment by sre42** [comment]
Great!, Do let me know If you want me to look into any 3D library.

**Comment by peterGraf** [comment]
Unity 3d solves the problem
