### ISSUE TITLE
Should ARVOS use  the JMonkeyEngine 3

### ISSUE THREAD

**Issue by peterGraf** [peterGraf/ARVOS#5]

**Comment by peterGraf** [comment]
I do not see a way to use the JMonkeyEngine 3 in iOS? Can anybody enlighten me?

**Comment by sre42** [comment]
These posts talks about JME on IOS. But since IOS deployment is in Alpha state, Ogre would be a better option. 

http://wiki.jmonkeyengine.org/doku.php/jme3:ios

http://hub.jmonkeyengine.org/t/my-experience-with-jme-on-ios/31192

**Comment by peterGraf** [comment]
Ok, then let's close the issue
