### ISSUE TITLE
Augments Server

### ISSUE THREAD

**Issue by sre42** [peterGraf/ARVOS#6]
Augments have to be stored and be retrievable on the clients.
One way to do this would be to develop a Spring based Java server that provides Rest services using the HTTP protocol(JSON format).

Will require a JSON  parser such as Retrofit for Android (for IOS?)

**Comment by sre42** [comment]
@peterGraf I have developed a starter Spring boot Arvos Server at: 
https://github.com/Omarasifshaikh/Arvos-server.git

**Comment by peterGraf** [comment]
Hello Omar, I guess, I'll have to hurry up and write some specification for
the server :-)

**Comment by sre42** [comment]
@peterGraf 
Hi Peter,
Great wiki write up at https://github.com/peterGraf/ARVOS/wiki/ARVOS-Directory-Service
A few questions:
Will Arvos have two separate server instances? one for the Augments directory and another for storing the Augments data?
Has the Directory service already been implemented? and will it be a part of the platform?
Thanks!

**Comment by peterGraf** [comment]
Hello Omar,

The idea is to have a single instance of the directory service running on the web. The url of this instance is hard coded into the client applications. 

So if a user starts a client application, the app uses that hard coded url and sends a 'list augments' request with its current location from the device to the directory service. 

The directory service replies with a augment list JSON response.

The client then displays the list of available augments to the user.

Once the user selects an augment, the app requests the augment details from the augment server url given with augment.

Once the augment server gives back the augments description JSON, the app displays the augment overlaying if over the camera image.

None of the server components is implemented so far.

Potentially each author could run a separate instance of the ARVOS augment server for serving the augments belonging to that author.

Therefore the augments server software needs to be very easy to install on a regular web server, of the kind you can rent from GoDaddy or such services.

**Comment by sre42** [comment]
Thanks @peterGraf for the elaborate response.
I will start working to build the directory server as per the specification.
